included:
  - Sources
  - iOSTests
  - Example

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_enum_arguments
  - empty_string
  - empty_xctest_method
  - expiring_todo
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - no_grouping_extension
  - nslocalizedstring_require_bundle
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Submodules

closure_body_length:
  warning: 30
  error: 40

number_separator:
  minimum_length: 5

modifier_order:
  preferred_modifier_order:
    - acl
    - override
    - final

line_length:
  warning: 160
  error: 200
  ignores_comments: true
  
type_body_length:
  warning: 300
  error: 400

function_body_length:
  warning: 60
  error: 120

vertical_whitespace:
  max_empty_lines: 2

file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  ViaSwiftUtils
                    \/\/
                    \/\/  Copyright \d{4} Viacom, Inc.
                    \/\/
                    \/\/  Licensed under the Apache License, Version 2\.0 \(the "License"\);
                    \/\/  you may not use this file except in compliance with the License\.
                    \/\/  You may obtain a copy of the License at
                    \/\/
                    \/\/  http:\/\/www.apache.org\/licenses\/LICENSE-2\.0
                    \/\/
                    \/\/  Unless required by applicable law or agreed to in writing, software
                    \/\/  distributed under the License is distributed on an "AS IS" BASIS,
                    \/\/  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied\.
                    \/\/  See the License for the specific language governing permissions and
                    \/\/  limitations under the License\.
